url: https://www.arraeofthings.com
baseurl: 

# Site settings
title: Arraeofthings
email: contact@arraeofthings.com
description: Arraeofthings · Visual artist and art director. 


# Build settings
markdown: kramdown
permalink: pretty